name: Activity 1 Tests

on:
  push:
    branches:
      - main  # Adjust this if you use a different branch as your default
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Convert Notebook to Script
      run: jupyter nbconvert --to script Python_Activity_1.ipynb  # Replace with your notebook name
    - name: Run Tests
      run: python -m unittest discover -s . -p "test_*.py"  # Adjust the pattern to match your test files
